services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db.sqlite3:/db.sqlite3
  frontend:
    restart: unless-stopped
    build: ./frontend
    ports:
      - "10000:3000"
    depends_on:
      - backend