services:
  backend:
    build: ./backend
    restart: unless-stopped
    volumes:
      - ./backend:/backend
  frontend:
    restart: unless-stopped
    build: ./frontend
    ports:
      - "10000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000