services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
  frontend:
    build: ./frontend
    ports:
      - "10000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true # bind mount on windows does not trigger file notification events, so we have to manually poll
      - CHOKIDAR_INTERVAL=1000 # polling interval set to 1000ms to reduce CPU load
