# Generated by Django 3.2.5 on 2021-11-11 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baseTodos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('effort', models.DecimalField(decimal_places=2, default=0.5, max_digits=6)),
                ('reward', models.DecimalField(decimal_places=2, default=0.5, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'baseTodos',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work')], default='Personal', max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('startdate', models.DateField(default=django.utils.timezone.now)),
                ('duedate', models.DateField(blank=True, null=True)),
                ('completedate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['type', 'startdate'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imgurl', models.CharField(max_length=400, null=True)),
                ('producturl', models.CharField(blank=True, max_length=400, null=True)),
                ('count', models.IntegerField(default=0, null=True)),
                ('repeat', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Wishlist',
                'ordering': ['-repeat', 'count', 'cost'],
            },
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('basetodos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todos.basetodos')),
                ('category', models.CharField(choices=[('Learning', 'Learning'), ('Financial', 'Financial'), ('Health', 'Health'), ('Social', 'Social')], default='Learning', max_length=20)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='Daily', max_length=20)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Habits',
                'ordering': ['category', 'frequency'],
            },
            bases=('todos.basetodos',),
        ),
        migrations.AddField(
            model_name='basetodos',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todos.projects'),
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('basetodos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todos.basetodos')),
                ('startdate', models.DateField(default=django.utils.timezone.now)),
                ('duedate', models.DateField(default=django.utils.timezone.now)),
                ('completedate', models.DateField(blank=True, null=True)),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habittodos', to='todos.habits')),
            ],
            options={
                'verbose_name_plural': 'Todos',
                'ordering': ['-completedate', 'duedate', 'startdate'],
            },
            bases=('todos.basetodos',),
        ),
    ]
