# Generated by Django 3.2.5 on 2021-12-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20211126_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='wishlist',
            name='last_purchased_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
