# Generated by Django 3.2.9 on 2021-12-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20211205_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('YEARLY', 'YEARLY')], default=None, max_length=20, null=True),
        ),
    ]
